//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algoloop.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Algoloop.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application update: {0}.
        /// </summary>
        internal static string AppUpdated {
            get {
                return ResourceManager.GetString("AppUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application updating {0}%.
        /// </summary>
        internal static string AppUpdating {
            get {
                return ResourceManager.GetString("AppUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration saved.
        /// </summary>
        internal static string ConfigurationSaved {
            get {
                return ResourceManager.GetString("ConfigurationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading configuration completed.
        /// </summary>
        internal static string LoadingConfigurationCompleted {
            get {
                return ResourceManager.GetString("LoadingConfigurationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market {0} completed.
        /// </summary>
        internal static string MarketCompleted {
            get {
                return ResourceManager.GetString("MarketCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market {0} failed: {1}.
        /// </summary>
        internal static string MarketException {
            get {
                return ResourceManager.GetString("MarketException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market {0} has no symbol selected.
        /// </summary>
        internal static string MarketNoSymbol {
            get {
                return ResourceManager.GetString("MarketNoSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market {0} started.
        /// </summary>
        internal static string MarketStarted {
            get {
                return ResourceManager.GetString("MarketStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update is available.
        /// </summary>
        internal static string NoAppUpdate {
            get {
                return ResourceManager.GetString("NoAppUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbol selected!.
        /// </summary>
        internal static string NoSymbolSelected {
            get {
                return ResourceManager.GetString("NoSymbolSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference symbol {0} already exist.
        /// </summary>
        internal static string ReferenceSymbolExist {
            get {
                return ResourceManager.GetString("ReferenceSymbolExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        internal static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings read failed. See logs for details.
        /// </summary>
        internal static string SettingsReadFailed {
            get {
                return ResourceManager.GetString("SettingsReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy aborted.
        /// </summary>
        internal static string StrategyAborted {
            get {
                return ResourceManager.GetString("StrategyAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy completed.
        /// </summary>
        internal static string StrategyCompleted {
            get {
                return ResourceManager.GetString("StrategyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy started with {0} backtest(s).
        /// </summary>
        internal static string StrategyStarted {
            get {
                return ResourceManager.GetString("StrategyStarted", resourceCulture);
            }
        }
    }
}
