<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Resources\AlgoloopIcon.ico</ApplicationIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.2" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.2.2" />
    <PackageReference Include="OxyPlot.Avalonia" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <!-- Note: Some project references are temporarily commented out until they are made cross-platform compatible -->
    <!--<ProjectReference Include="..\Algoloop.Wpf.Model\Algoloop.Wpf.Model.csproj" />-->
    <ProjectReference Include="..\Algoloop\Algoloop.csproj" />
    <!--<ProjectReference Include="..\Algorithm.CSharp\QuantConnect.Algorithm.CSharp.csproj" />-->
    <!--<ProjectReference Include="..\Capnode.Wpf\Capnode.Wpf.csproj" />-->
    <!--<ProjectReference Include="..\Launcher\QuantConnect.Lean.Launcher.csproj" />-->
    <!--<ProjectReference Include="..\Research\QuantConnect.Research.csproj" />-->
    <!--<ProjectReference Include="..\ToolBox\QuantConnect.ToolBox.csproj" />-->
  </ItemGroup>

</Project>
