//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Algoloop.Wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MainWindowPlacement {
            get {
                return ((string)(this["MainWindowPlacement"]));
            }
            set {
                this["MainWindowPlacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220")]
        public int StrategyViewSplitter {
            get {
                return ((int)(this["StrategyViewSplitter"]));
            }
            set {
                this["StrategyViewSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int AccountViewSplitter {
            get {
                return ((int)(this["AccountViewSplitter"]));
            }
            set {
                this["AccountViewSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public int MarketViewSplitter {
            get {
                return ((int)(this["MarketViewSplitter"]));
            }
            set {
                this["MarketViewSplitter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BacktestsColumnsInfo {
            get {
                return ((string)(this["BacktestsColumnsInfo"]));
            }
            set {
                this["BacktestsColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountBalanceColumnsInfo {
            get {
                return ((string)(this["AccountBalanceColumnsInfo"]));
            }
            set {
                this["AccountBalanceColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountOrdersColumnsInfo {
            get {
                return ((string)(this["AccountOrdersColumnsInfo"]));
            }
            set {
                this["AccountOrdersColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountPositionsColumnsInfo {
            get {
                return ((string)(this["AccountPositionsColumnsInfo"]));
            }
            set {
                this["AccountPositionsColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AccountClosedTradesColumnsInfo {
            get {
                return ((string)(this["AccountClosedTradesColumnsInfo"]));
            }
            set {
                this["AccountClosedTradesColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MarketSymbolsColumnsInfo {
            get {
                return ((string)(this["MarketSymbolsColumnsInfo"]));
            }
            set {
                this["MarketSymbolsColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MarketSymbolListsColumnsInfo {
            get {
                return ((string)(this["MarketSymbolListsColumnsInfo"]));
            }
            set {
                this["MarketSymbolListsColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BacktestHoldingsColumnsInfo {
            get {
                return ((string)(this["BacktestHoldingsColumnsInfo"]));
            }
            set {
                this["BacktestHoldingsColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BacktestTradesColumnsInfo {
            get {
                return ((string)(this["BacktestTradesColumnsInfo"]));
            }
            set {
                this["BacktestTradesColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BacktestOrdersColumnsInfo {
            get {
                return ((string)(this["BacktestOrdersColumnsInfo"]));
            }
            set {
                this["BacktestOrdersColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BacktestDetailsColumnsInfo {
            get {
                return ((string)(this["BacktestDetailsColumnsInfo"]));
            }
            set {
                this["BacktestDetailsColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Theme {
            get {
                return ((string)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FundamentalsColumnsInfo {
            get {
                return ((string)(this["FundamentalsColumnsInfo"]));
            }
            set {
                this["FundamentalsColumnsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MarketViewChartSettings {
            get {
                return ((string)(this["MarketViewChartSettings"]));
            }
            set {
                this["MarketViewChartSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BacktestViewChartSettings {
            get {
                return ((string)(this["BacktestViewChartSettings"]));
            }
            set {
                this["BacktestViewChartSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BacktestViewPlotSettings {
            get {
                return ((string)(this["BacktestViewPlotSettings"]));
            }
            set {
                this["BacktestViewPlotSettings"] = value;
            }
        }
    }
}
